### ISSUE TITLE
what number requests to the API ?

### ISSUE THREAD

**Issue by Rot4tion** [barbarbar338/bh-open-api#3]
{"statusCode":429,"message":"Rate limit exceeded"}

**Comment by barbarbar338** [comment]
https://github.com/barbarbar338/bh-open-api/blob/e0ba6961944607e91312af1b992f82391924ae05/src/app.module.ts#L19 its 60 reqs per hour

**Comment by barbarbar338** [comment]
https://github.com/barbarbar338/bh-open-api/blob/e0ba6961944607e91312af1b992f82391924ae05/src/config.ts#L13

And 1 req per 2 hour for force syncing
