### ISSUE TITLE
Because of Brawlhalla api changes we can not search players using their names

### ISSUE THREAD

**Issue by MuffinCat1** [barbarbar338/bh-open-api#5]
so I'm trying to use this endpoint: "https://brawlhalla.fly.dev/v1/ranked/name?name=(a name)" and all I get is an error with the API saying an error occurred: Cannot read properties of undefined (reading 'name'). when I tried the examples on your website to see if this thing works, it didn't work as well said: "couldn't find that player" with the player name that you have put there, so please can you check it and maybe replace it if need.

**Comment by barbarbar338** [comment]
I'll check it asap

**Comment by MuffinCat1** [comment]
well... any update?

**Comment by barbarbar338** [comment]
currently investigating the problem

**Comment by MuffinCat1** [comment]
are there any changes in the situation?

**Comment by barbarbar338** [comment]
it looks like some brawlhalla api endpoints are changed so im trying to find a new way to find people by their name

**Comment by MuffinCat1** [comment]
pls tell me when u fixed it

**Comment by barbarbar338** [comment]
I forgot to mention it here but it is fixed.
